services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.1.4@sha256:85214df20cd7bc020f8e4b0f60f87ea87f0a754ca7ba3d1ccdfc503ccd6e7f9c
    container_name: n8n
    user: "1000:1000"
    restart: unless-stopped
    environment:
      - GENERIC_TIMEZONE=${TIMEZONE}
      - TZ=${TIMEZONE}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - USER_UID=1000
      - USER_GID=1000
      - N8N_HOST=n8n.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_PROXY_HOPS=1
      - WEBHOOK_URL=https://n8n.${DOMAIN_NAME}/
      - N8N_EDITOR_BASE_URL=https://n8n.${DOMAIN_NAME}/
      - NODE_FUNCTION_ALLOW_EXTERNAL=cheerio
      - N8N_LOG_LEVEL=info
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`n8n.${DOMAIN_NAME}`)
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.tls.certresolver=myclouddns
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - traefik.http.routers.n8n.middlewares=geoblock@file,crowdsec-bouncer@docker,authelia-forwardauth@docker
      - homepage.group=Other
      - homepage.name=n8n
      - homepage.icon=n8n.png
      - homepage.href=http://n8n.${DOMAIN_NAME}/
      - homepage.description=Workflow automation tool
    volumes:
      - ${DATADIR}/n8n:/home/node/.n8n
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - internal

networks:
  internal:
    external: true
