services:
  authelia:
    image: authelia/authelia:4.39.14@sha256:88f1494b6ac1174641770f106335ab67752d66e5822b4059badca220b5d6153b
    container_name: authelia
    user: "1000:1000"
    restart: unless-stopped
    environment:
      - X_AUTHELIA_CONFIG_FILTERS=template
      - TZ=${TIMEZONE}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - STORAGE_ENCRYPTION_KEY=${STORAGE_ENCRYPTION_KEY}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    volumes:
      - ${CONFIGDIR}/authelia/config:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`auth.${DOMAIN_NAME}`)
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.tls=true
      - traefik.http.routers.authelia.tls.certresolver=myclouddns
      - traefik.http.routers.authelia.middlewares=geoblock@file,crowdsec-bouncer@docker
      - traefik.http.services.authelia.loadbalancer.server.port=9091
      # ForwardAuth middleware for reuse on apps:
      - traefik.http.middlewares.authelia-forwardauth.forwardauth.address=http://authelia:9091/api/authz/forward-auth
      - traefik.http.middlewares.authelia-forwardauth.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authelia-forwardauth.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
      - traefik.http.middlewares.authelia-forwardauth.forwardauth.authResponseHeadersRegex=^Remote-
    networks:
      - internal

networks:
  internal:
    external: true