services:
  radarr:
    image: lscr.io/linuxserver/radarr:5.28.0@sha256:c984533510abe0219a70e80d15bd0d212b7df21baa0913759c4ce6cc9092240b
    container_name: radarr
    volumes:
      - ${DATADIR}/radarr/config:/config
      - ${DATADIR}/library:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN_NAME}`)
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.tls.certresolver=myclouddns
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.routers.radarr.middlewares=geoblock@file,crowdsec-bouncer@docker,authelia-forwardauth@docker
      - homepage.group=Servarr
      - homepage.name=Radarr
      - homepage.icon=radarr.png
      - homepage.href=http://radarr.${DOMAIN_NAME}/
      - homepage.description=Manages and downloads movies
      - homepage.widget.type=radarr
      - homepage.widget.url=http://radarr:7878
      - homepage.widget.key=${RADARR_API_KEY}
      - homepage.widget.enableQueue=true
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    external: true