services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:v1.7.0@sha256:b6ac42c31845ea7c862d71451c16413a6284430d8ff08e16ad791f42718a7c71
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`home.${DOMAIN_NAME}`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.tls=true
      - traefik.http.routers.homepage.tls.certresolver=myclouddns
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - traefik.http.routers.homepage.middlewares=geoblock@file,crowdsec-bouncer@docker,authelia-forwardauth@docker
    environment:
      - UMASK=002
      - TZ=${TIMEZONE}
      - HOMEPAGE_ALLOWED_HOSTS=${LOCAL_IP}:5000,home.${DOMAIN_NAME}
    volumes:
      - ${CONFIGDIR}/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    tmpfs:
      - /app/logs
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    external: true