services:
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:v1.9.1@sha256:03b402335881cdab2e4939b24620809df8d6ceec3bf2712217d41c8761a0f5d4
    container_name: whisper
    environment:
      ASR_MODEL: base
      ASR_ENGINE: openai_whisper
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    external: true
