services:
  sablier:
    image: sablierapp/sablier:1.11.0@sha256:3bd2c107b581cac4cea358d57c580d2fe298f2f860adccc281b83469b5e738f3
    container_name: sablier
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TIMEZONE}
      - PROVIDER_NAME=docker
      - STRATEGY_DYNAMIC_SHOW_DETAILES_BY_DEFAULT=true
      - PROVIDER_DOCKER_STRATEGY=stop
    networks:
      - internal

networks:
  internal:
    external: true

