services:
  prefetcharr:
    image: phueber/prefetcharr:latest@sha256:8f3a65a8faf257eb556816957da052c04fe2c653e7fa433633fe3d7e952ade8e
    container_name: prefetcharr
    volumes:
      # Copy prefetcharr.toml to your ${DATADIR} and set the api keys for jellyfin and sonarr 
      - ${DATADIR}/prefetcharr/prefetcharr.toml:/config
    environment:
      - PREFETCHARR_CONFIG=/config
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    external: true