services:
  prefetcharr:
    image: phueber/prefetcharr:latest@sha256:b191e1bde981fdb125bedb52bfbad0210e4cf0fe49dc36b83b6fb75cd5d5b1aa
    container_name: prefetcharr
    volumes:
      # Copy prefetcharr.toml to your ${DATADIR} and set the api keys for jellyfin and sonarr 
      - ${DATADIR}/prefetcharr/prefetcharr.toml:/config
    environment:
      - PREFETCHARR_CONFIG=/config
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    external: true