services:
  prefetcharr:
    image: phueber/prefetcharr:latest@sha256:eeff3fcd5e52ccc90abcf7e0d10139f25b3fbc3695a188c61110c346cfacd1be
    container_name: prefetcharr
    volumes:
      # Copy prefetcharr.toml to your ${DATADIR} and set the api keys for jellyfin and sonarr 
      - ${DATADIR}/prefetcharr/prefetcharr.toml:/config
    environment:
      - PREFETCHARR_CONFIG=/config
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    external: true