services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:1.5.3@sha256:ec11e988e8e13411c994a4d9f43ed9b97409aa92c1da54d9f23926c3da7c2032
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK=002
    volumes:
      - ${DATADIR}/bazarr/config:/config
      - ${DATADIR}/library/media:/data/media
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAIN_NAME}`)
      - traefik.http.routers.bazarr.entrypoints=websecure
      - traefik.http.routers.bazarr.tls=true
      - traefik.http.routers.bazarr.tls.certresolver=myclouddns
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
      - traefik.http.routers.bazarr.middlewares=geoblock@file,crowdsec-bouncer@docker,authelia-forwardauth@docker
      - homepage.group=Servarr
      - homepage.name=Bazarr
      - homepage.icon=bazarr.png
      - homepage.href=http://bazarr.${DOMAIN_NAME}/
      - homepage.description=Manages and downloads subtitles
      - homepage.widget.type=bazarr
      - homepage.widget.url=http://bazarr:6767
      - homepage.widget.key=${BAZARR_API_KEY}
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    external: true
